spring:
  profiles: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: einsetzen
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: einsetzen
    username: einsetzen
    password: einsetzen
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: create-drop
#      ddl-auto: create
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: true
        format_sql: true
  mail:
    default-encoding: UTF-8
    host: einsetzen
    username: einsetzen
    password: einsetzen
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  freemarker:
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
  messages:
    basename: messages

logging:
  level:
    root: WARN
    io.remedymatch: INFO
    
io:
  remedymatch:
    engine: 
      externalTaskUrl: http://www.remedymatch.io/engine/rest
    frontend:
      url: http://www.remedymatch.io/app
    website:
      impressumUrl: http://www.remedymatch.io/impressum
      emailLogoUrl: http://www.remedymatch.io/assets/images/logo/mail-logo.png
    email:
      from: bittenichtantworten@remedymatch.io
